server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: avinaash
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet